import fs from 'node:fs/promises';
import path from 'node:path';
import {spawn} from 'node:child_process';
const dir=path.resolve('.scratch/keybindings-qa'),profile=path.join(dir,`chrome-${Date.now()}`);
await fs.mkdir(profile,{recursive:true});
const chrome=spawn('C:/Program Files/Google/Chrome/Application/chrome.exe',['--headless=new','--disable-gpu','--no-first-run','--remote-debugging-port=0',`--user-data-dir=${profile}`,'about:blank'],{windowsHide:true,stdio:'ignore'});
let socket;
const delay=ms=>new Promise(r=>setTimeout(r,ms));
try {
 let port;for(let i=0;i<300;i++){try{port=Number((await fs.readFile(path.join(profile,'DevToolsActivePort'),'utf8')).split('\n')[0]);break;}catch{await delay(200);}}
 if(!port)throw Error('No Chrome endpoint');
 const tabs=await(await fetch(`http://127.0.0.1:${port}/json/list`)).json();socket=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise((r,j)=>{socket.onopen=r;socket.onerror=j;});
 let seq=0;const pending=new Map(),errors=[];
 socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p?.reject(m.error):p?.resolve(m.result);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);};
 const cdp=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});
 const evaluate=async expression=>{const r=await cdp('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result?.value;};
 const shot=async name=>{const r=await cdp('Page.captureScreenshot',{format:'png'});await fs.writeFile(path.join(dir,name+'.png'),Buffer.from(r.data,'base64'));};
 await cdp('Page.enable');await cdp('Runtime.enable');await cdp('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
 await cdp('Page.addScriptToEvaluateOnNewDocument',{source:`
 window.__qaCalls=[];window.__qaCancel=false;let callback=0;
 const session={id:'qa-session',name:'w1.qa',shell:'powershell.exe',cwd:'C:\\\\qa-project',cols:100,rows:24,agent:'terminal'};
 localStorage.setItem('winmux:workspaces:v1',JSON.stringify({version:1,store:{activeWorkspaceId:'qa-project',workspaces:[{id:'qa-project',name:'QA Project',index:1,nextSessionSeq:2,settings:{defaultCwd:'C:\\\\qa-project',terminal:null},layout:{kind:'leaf',id:'qa-leaf',tabs:['qa-session'],activeTabId:'qa-session'},terminalSnapshots:{}}]}}));
 window.__TAURI_INTERNALS__={metadata:{currentWindow:{label:'main'},currentWebview:{label:'main'}},transformCallback:()=>++callback,unregisterCallback:()=>{},invoke:async(command,args={})=>{window.__qaCalls.push({command,args});if(command==='list_sessions')return [session];if(command==='create_session')return session;if(command==='attach_session')return btoa('PS C:\\\\qa-project> ');if(command==='flow_request')return {workers:[],flows:[],tasks:[],runs:[]};if(command==='read_directory')return {path:args.path,entries:[]};if(command==='plugin:dialog|save')return window.__qaCancel?null:'C:\\\\qa-project\\\\qa-note.txt';if(command==='plugin:event|listen')return ++callback;if(command.includes('is_'))return false;if(command==='list_files')return {root:args.root,files:[]};return null;}};
 window.__TAURI_EVENT_PLUGIN_INTERNALS__={unregisterListener:()=>{}};
 `});
 await cdp('Page.navigate',{url:'http://127.0.0.1:43339/'});
 for(let i=0;i<100;i++){if(await evaluate("!!document.querySelector('.terminal-menu-toggle')"))break;await delay(500);}
 await delay(1500);
 const assert=(v,m)=>{if(!v)throw Error(m);};
 const press=async(key,code,virtualKey,modifiers=0)=>{await cdp('Input.dispatchKeyEvent',{type:'keyDown',key,code,windowsVirtualKeyCode:virtualKey,modifiers});await cdp('Input.dispatchKeyEvent',{type:'keyUp',key,code,windowsVirtualKeyCode:virtualKey,modifiers});await delay(80);};
 const row=id=>`[data-action-id="${id}"]`;
 const click=selector=>evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);
 const text=selector=>evaluate(`document.querySelector(${JSON.stringify(selector)})?.textContent.trim()`);
 const focus=()=>evaluate("document.querySelector('.xterm-helper-textarea').focus()");
 const openSettings=async()=>{await press(',','Comma',188,2);await delay(200);await evaluate("document.querySelectorAll('.settings-shell .nav-item')[4].click()");await delay(150);};
 const back=async()=>{await click('.back-to-app');await delay(150);await focus();};
 const toast=()=>text('.terminal-zoom-toast');
 console.log("initial",await evaluate("({body:document.body.innerText.slice(0,300),url:location.href})"),errors);
 await focus();await openSettings();
 assert(await text(row('terminal.zoomIn')+' .key-cell')==='Ctrl+Shift++','Default zoom missing');
 assert(await evaluate("document.querySelectorAll('[data-action-id]').length")===60,'Registry rows missing');
 await shot('shortcuts-desktop');
 await click(row('terminal.zoomIn')+' .key-cell');await press('F8','F8',119);
 assert(await text(row('terminal.zoomIn')+' .key-cell')==='F8','Capture F8 failed');
 await click(row('terminal.zoomInWheel')+' .key-cell');
 await cdp('Input.dispatchMouseEvent',{type:'mouseWheel',x:650,y:300,deltaX:0,deltaY:-120,modifiers:1});await delay(150);
 await click(row('prefix.activate')+' .key-cell');await press('a','KeyA',65,2);
 await click(row('view.toggleLeftPanel')+' .prefix-cell');await press('x','KeyX',88);
 await click(row('view.toggleLeftPanel')+' .key-cell');await press('F9','F9',120);
 await click(row('editor.save')+' .key-cell');await press('F7','F7',118);
 await click(row('terminal.paste')+' .key-cell');await press('F6','F6',117);
 await click(row('terminal.copy')+' .key-cell');await press('F5','F5',116);
 await click(row('session.new')+' .key-cell');await press('Escape','Escape',27);
 assert(await evaluate("!!document.querySelector('.settings-shell')"),'Esc capture closed settings');
 assert(await text(row('session.new')+' .key-cell')==='Ctrl+N','Esc capture changed binding');
 await delay(200);await back();
 await press('F8','F8',119);assert(await toast()==='110%','New zoom shortcut failed');
 await delay(1400);await press('+','Equal',187,10);assert(!await toast(),'Old shortcut still zooms');
 const pos=await evaluate("(()=>{const r=document.querySelector('.term-host').getBoundingClientRect();return {x:r.x+80,y:r.y+80}})()");
 await cdp('Input.dispatchMouseEvent',{type:'mouseWheel',...pos,deltaX:0,deltaY:-120,modifiers:10});await delay(150);assert(!await toast(),'Old wheel still zooms');
 await cdp('Input.dispatchMouseEvent',{type:'mouseWheel',...pos,deltaX:0,deltaY:-120,modifiers:1});await delay(150);assert(await toast()==='120%','New wheel failed');
 await focus();await press('a','KeyA',65,2);await press('x','KeyX',88);assert(!await evaluate("!!document.querySelector('.region-left')"),'Custom prefix sequence failed');
 await focus();await press('F9','F9',120);assert(await evaluate("!!document.querySelector('.region-left')"),'Custom global function key failed');
 await evaluate("Object.defineProperty(navigator,'clipboard',{configurable:true,value:{readText:async()=> 'QA paste',writeText:async(text)=>{window.__copied=text;}}})");
 const writes=()=>evaluate("__qaCalls.filter(c=>c.command==='write_session')");const beforePaste=await writes();
 await press('F6','F6',117);const afterPaste=await writes();assert(afterPaste.length===beforePaste.length+1,'Custom paste duplicate/missing');
 assert(Buffer.from(afterPaste.at(-1).args.data,'base64').toString()==='QA paste','Paste content wrong');
 await press('V','KeyV',86,10);assert((await writes()).length===afterPaste.length,'Old paste still active');
 await press('F5','F5',116);assert((await writes()).length===afterPaste.length,'Copy without selection writes to PTY');
 await cdp('Page.reload');await delay(2200);await focus();await press('F8','F8',119);assert(await toast()==='110%','Zoom binding not persisted');
 await openSettings();assert(await text(row('prefix.activate')+' .key-cell')==='Ctrl+A','Prefix binding not persisted');
 assert(await text(row('view.toggleLeftPanel')+' .prefix-cell').then(t=>t.endsWith('x')),'Prefix second key not persisted');
 await click(row('terminal.zoomIn')+' .key-cell');
 await evaluate(`document.querySelector('${row('terminal.zoomIn')} .key-cell').dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true}))`);
 assert(!await evaluate("!!document.querySelector('.capturing')"),'Clear did not cancel capture');
 await back();await delay(1400);await press('F8','F8',119);assert(!await toast(),'Cleared binding still zooms');
 await openSettings();await click(row('terminal.zoomIn')+' .reset');await back();await press('+','Equal',187,10);assert(await toast()==='120%','Reset binding failed');
 await openSettings();await cdp('Emulation.setDeviceMetricsOverride',{width:800,height:600,deviceScaleFactor:1,mobile:false});await delay(150);await shot('shortcuts-small');
 assert(await evaluate("document.documentElement.scrollWidth<=innerWidth"),'Settings overflow');
 await back();await click('.terminal-menu-toggle');await delay(100);await click('.terminal-option');
 for(let i=0;i<100;i++){if(await evaluate("!!document.querySelector('.monaco-editor')"))break;await delay(200);}
 await delay(300);await cdp('Input.insertText',{text:'QA custom save'});
 await press('F7','F7',118);await delay(400);const fileWrites=await evaluate("__qaCalls.filter(c=>c.command==='write_file')");assert(fileWrites.length===1&&fileWrites[0].args.contents==='QA custom save','Remapped file save failed');
 await press('s','KeyS',83,2);assert(await evaluate("__qaCalls.filter(c=>c.command==='write_file').length")===1,'Old save shortcut still active');
 await click('.pane .tab');await delay(150);await focus();await openSettings();
 await click('.reset-all');await delay(200);assert(await text(row('prefix.activate')+' .key-cell')==='Ctrl+B','Reset all prefix failed');
 assert(await text(row('view.toggleLeftPanel')+' .key-cell')==='Ctrl+Shift+B','Reset all direct failed');
 const report={rows:60,keyboardRemap:true,wheelRemap:true,prefixRemap:true,globalFunctionKey:true,persistence:true,clear:true,reset:true,captureEscape:true,responsive:true,clipboard:true,fileSave:true,errors};assert(!errors.length,'Browser exceptions');
 await fs.writeFile(path.join(dir,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
}finally{socket?.close();chrome.kill();}
